export default Object.freeze({
    TODOS_SEARCH_TASK: 'TODOS_SEARCH_TASK',
    TODOS_RESET:       'TODOS_RESET',

    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL:    'CREATE_TASK_FAIL',

    READ_TASK:         'READ_TASK',
    READ_TASK_SUCCESS: 'READ_TASK_SUCCESS',
    READ_TASK_FAIL:    'READ_TASK_FAIL',

    UPDATE_TASK:         'UPDATE_TASK',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAIL:    'UPDATE_TASK_FAIL',

    DELETE_TASK:         'DELETE_TASK',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAIL:    'DELETE_TASK_FAIL',

    CHANGE_PRIORITY: 'CHANGE_PRIORITY',
    COMPLETE_TASK:   'COMPLETE_TASK',
    ALL_COMPLETE:    'ALL_COMPLETE',

    CHANGE_PRIORITY_SUCCESS: 'CHANGE_PRIORITY_SUCCESS',
    ALL_COMPLETE_SUCCESS:    'ALL_COMPLETE_SUCCESS',
    COMPLETE_TASK_SUCCESS:   'COMPLETE_TASK_SUCCESS',
});
