export default Object.freeze({
    TODOS_ALL_COMPLETE:         'TODOS_ALL_COMPLETE',
    TODOS_SEARCH_TASK:          'TODOS_SEARCH_TASK',
    TODOS_ADD_TASK:             'TODOS_ADD_TASK',
    TODOS_UPDATE_TASK:          'TODOS_UPDATE_TASK',
    TODOS_TASK_COMPLETE:        'TODOS_TASK_COMPLETE',
    TODOS_TASK_CHANGE_PRIORITY: 'TODOS_TASK_CHANGE_PRIORITY',
});
